@extends('layouts.app')

@section('title', 'Transactional Email Previews — Comme')

@section('content')
<!-- Hero Section -->
<section style="margin-bottom: 36px; border-bottom: 1px solid var(--border-subtle); padding-bottom: 32px;">
    <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 12px;">
        <span class="auth-badge" style="background: rgba(168, 2, 245, 0.14); color: var(--param-name-color); border-color: rgba(168, 2, 245, 0.3);">
            Transactional Mailer
        </span>
        <span style="font-size: 13px; color: var(--text-muted);">Live HTML & Plaintext Email Inspector</span>
    </div>

    <h1 class="heading-gradient" style="font-size: 34px; font-weight: 800; letter-spacing: -0.03em; margin-bottom: 14px;">
        Email Templates & Previews
    </h1>

    <p style="font-size: 15px; color: var(--text-secondary); max-width: 800px; line-height: 1.65; margin-bottom: 24px;">
        Preview all transactional emails generated by Comme. Test responsiveness across desktop and mobile viewports, inspect email metadata headers, and verify plaintext fallback content.
    </p>

    <!-- Template Selector Tabs -->
    <div style="display: flex; flex-wrap: wrap; gap: 10px; margin-top: 20px;">
        <button
            type="button"
            class="btn-copy email-tab active"
            data-template="reset-password"
            data-subject="Reset Your Password"
            onclick="switchEmail('reset-password', 'Reset Your Password')"
            style="font-size: 13px; font-weight: 700; padding: 8px 16px; border-radius: 8px; display: flex; align-items: center; gap: 8px;"
        >
            <span>🔑 Reset Password</span>
        </button>

        <button
            type="button"
            class="btn-copy email-tab"
            data-template="registration-code"
            data-subject="Verify your email - Your registration code"
            onclick="switchEmail('registration-code', 'Verify your email - Your registration code')"
            style="font-size: 13px; font-weight: 700; padding: 8px 16px; border-radius: 8px; display: flex; align-items: center; gap: 8px;"
        >
            <span>🔢 Registration OTP</span>
        </button>

        <button
            type="button"
            class="btn-copy email-tab"
            data-template="password-changed"
            data-subject="Security Alert: Password Changed"
            onclick="switchEmail('password-changed', 'Security Alert: Password Changed')"
            style="font-size: 13px; font-weight: 700; padding: 8px 16px; border-radius: 8px; display: flex; align-items: center; gap: 8px;"
        >
            <span>🛡️ Password Changed</span>
        </button>

        <button
            type="button"
            class="btn-copy email-tab"
            data-template="new-device"
            data-subject="Security Alert: New device sign-in"
            onclick="switchEmail('new-device', 'Security Alert: New device sign-in')"
            style="font-size: 13px; font-weight: 700; padding: 8px 16px; border-radius: 8px; display: flex; align-items: center; gap: 8px;"
        >
            <span>💻 New Device Sign-in</span>
        </button>
    </div>
</section>

<!-- Email Preview Workspace -->
<div style="display: flex; flex-direction: column; gap: 18px;">
    <!-- Controls Bar -->
    <div style="background: var(--bg-surface); border: 1px solid var(--border-subtle); border-radius: 12px; padding: 14px 20px; display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 14px;">
        <!-- Left: Format Switcher (HTML vs Plaintext) -->
        <div style="display: flex; align-items: center; gap: 8px;">
            <span style="font-size: 12px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.04em;">Format:</span>
            <div style="display: flex; background: var(--bg-surface-elevated); border: 1px solid var(--border-subtle); border-radius: 8px; padding: 3px;">
                <button
                    id="btnFormatHtml"
                    type="button"
                    onclick="setFormat('html')"
                    style="border: none; background: var(--brand-purple); color: #ffffff; padding: 5px 12px; border-radius: 6px; font-size: 12px; font-weight: 700; cursor: pointer; transition: all 0.15s ease;"
                >
                    HTML
                </button>
                <button
                    id="btnFormatText"
                    type="button"
                    onclick="setFormat('text')"
                    style="border: none; background: transparent; color: var(--text-secondary); padding: 5px 12px; border-radius: 6px; font-size: 12px; font-weight: 600; cursor: pointer; transition: all 0.15s ease;"
                >
                    Plain Text
                </button>
            </div>
        </div>

        <!-- Middle: Viewport Switcher -->
        <div style="display: flex; align-items: center; gap: 8px;">
            <span style="font-size: 12px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.04em;">Viewport:</span>
            <div style="display: flex; background: var(--bg-surface-elevated); border: 1px solid var(--border-subtle); border-radius: 8px; padding: 3px;">
                <button
                    id="btnViewportDesktop"
                    type="button"
                    onclick="setViewport('600px')"
                    title="Desktop Email Width (600px)"
                    style="border: none; background: var(--brand-purple); color: #ffffff; padding: 5px 12px; border-radius: 6px; font-size: 12px; font-weight: 700; cursor: pointer; transition: all 0.15s ease;"
                >
                    Desktop (600px)
                </button>
                <button
                    id="btnViewportMobile"
                    type="button"
                    onclick="setViewport('380px')"
                    title="Mobile Viewport (380px)"
                    style="border: none; background: transparent; color: var(--text-secondary); padding: 5px 12px; border-radius: 6px; font-size: 12px; font-weight: 600; cursor: pointer; transition: all 0.15s ease;"
                >
                    Mobile (380px)
                </button>
                <button
                    id="btnViewportFull"
                    type="button"
                    onclick="setViewport('100%')"
                    title="Full Width"
                    style="border: none; background: transparent; color: var(--text-secondary); padding: 5px 12px; border-radius: 6px; font-size: 12px; font-weight: 600; cursor: pointer; transition: all 0.15s ease;"
                >
                    100%
                </button>
            </div>
        </div>

        <!-- Right: Actions -->
        <div style="display: flex; align-items: center; gap: 10px;">
            <a
                id="openNewTabLink"
                href="{{ url('/emails/render/reset-password') }}"
                target="_blank"
                rel="noopener noreferrer"
                class="btn-copy"
                style="text-decoration: none; font-size: 12px; display: flex; align-items: center; gap: 6px;"
            >
                <span>Open in New Tab</span>
                <span style="font-size: 10px; color: var(--brand-teal);">↗</span>
            </a>
            <button
                type="button"
                class="btn-copy"
                onclick="reloadEmailFrame()"
                style="font-size: 12px;"
            >
                ↻ Refresh
            </button>
        </div>
    </div>

    <!-- Email Envelope Card -->
    <div style="background: var(--bg-surface); border: 1px solid var(--border-subtle); border-radius: 14px; overflow: hidden; box-shadow: 0 8px 30px rgba(0, 0, 0, 0.25);">
        <!-- Envelope Headers -->
        <div style="background: var(--bg-surface-elevated); border-bottom: 1px solid var(--border-subtle); padding: 18px 24px; display: flex; flex-direction: column; gap: 8px;">
            <div style="display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: 10px;">
                <h3 id="emailSubjectDisplay" style="font-size: 16px; font-weight: 800; color: var(--text-primary); letter-spacing: -0.01em; margin: 0;">
                    Reset Your Password
                </h3>
                <span style="font-size: 11px; font-family: 'JetBrains Mono', monospace; color: var(--text-muted);">
                    {{ now()->format('M j, Y • g:i A T') }}
                </span>
            </div>

            <div style="display: flex; flex-wrap: wrap; gap: 16px; font-size: 12px; color: var(--text-secondary); margin-top: 4px;">
                <div>
                    <span style="color: var(--text-muted); font-weight: 600;">From:</span>
                    <span style="color: var(--text-primary); font-weight: 500;">Comme Security &lt;noreply@comme.art&gt;</span>
                </div>
                <div>
                    <span style="color: var(--text-muted); font-weight: 600;">To:</span>
                    <span style="color: var(--text-primary); font-weight: 500;">Alex Rivera &lt;alex@example.com&gt;</span>
                </div>
                <div>
                    <span style="color: var(--text-muted); font-weight: 600;">Template:</span>
                    <code id="templatePathDisplay" style="color: var(--param-name-color); font-size: 11px;">emails.auth.reset-password</code>
                </div>
            </div>
        </div>

        <!-- Render Viewport Area -->
        <div style="background: var(--bg-code); padding: 36px 16px; display: flex; justify-content: center; min-height: 520px; transition: all 0.3s ease;">
            <!-- HTML Render Frame -->
            <div id="frameWrapper" style="width: 600px; max-width: 100%; transition: width 0.3s cubic-bezier(0.16, 1, 0.3, 1);">
                <iframe
                    id="emailPreviewFrame"
                    src="{{ url('/emails/render/reset-password?format=html') }}"
                    style="width: 100%; height: 560px; border: 1px solid var(--border-subtle); border-radius: 8px; background: #ffffff; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);"
                    title="Live Email Preview"
                ></iframe>
            </div>

            <!-- Plain Text View Container (hidden by default) -->
            <div id="textPreviewWrapper" style="display: none; width: 680px; max-width: 100%;">
                <div class="code-container" style="margin: 0; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.25);">
                    <div class="code-header" style="display: flex; justify-content: space-between; align-items: center;">
                        <span>Plaintext Fallback (text/plain)</span>
                        <button class="btn-copy" onclick="copyPlaintext(this)" style="font-size: 11px; padding: 3px 8px;">Copy Plaintext</button>
                    </div>
                    <pre id="textPreviewContent" class="code-block" style="max-height: 560px; overflow-y: auto; white-space: pre-wrap; font-size: 13px; line-height: 1.65; color: var(--text-primary); padding: 24px;"></pre>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    let currentTemplate = 'reset-password';
    let currentSubject = 'Reset Your Password';
    let currentFormat = 'html';
    let currentViewport = '600px';

    function updatePreview() {
        const frame = document.getElementById('emailPreviewFrame');
        const frameWrapper = document.getElementById('frameWrapper');
        const textWrapper = document.getElementById('textPreviewWrapper');
        const textContent = document.getElementById('textPreviewContent');
        const openLink = document.getElementById('openNewTabLink');
        const templateDisplay = document.getElementById('templatePathDisplay');
        const subjectDisplay = document.getElementById('emailSubjectDisplay');

        // Update displays
        subjectDisplay.innerText = currentSubject;
        templateDisplay.innerText = `emails.auth.${currentTemplate}${currentFormat === 'text' ? '-text' : ''}`;
        openLink.href = `/emails/render/${currentTemplate}?format=${currentFormat}`;

        if (currentFormat === 'html') {
            frameWrapper.style.display = 'block';
            textWrapper.style.display = 'none';
            frameWrapper.style.width = currentViewport;
            frame.src = `/emails/render/${currentTemplate}?format=html&t=${Date.now()}`;
        } else {
            frameWrapper.style.display = 'none';
            textWrapper.style.display = 'block';
            textContent.innerText = 'Loading plaintext representation...';

            fetch(`/emails/render/${currentTemplate}?format=text`)
                .then(r => r.text())
                .then(text => {
                    textContent.innerText = text;
                })
                .catch(() => {
                    textContent.innerText = 'Error loading plaintext format.';
                });
        }
    }

    function switchEmail(template, subject) {
        currentTemplate = template;
        currentSubject = subject;

        document.querySelectorAll('.email-tab').forEach(tab => {
            const isActive = tab.dataset.template === template;
            tab.classList.toggle('active', isActive);
            if (isActive) {
                tab.style.background = 'rgba(168, 2, 245, 0.15)';
                tab.style.color = 'var(--param-name-color)';
                tab.style.borderColor = 'var(--brand-purple)';
            } else {
                tab.style.background = '';
                tab.style.color = '';
                tab.style.borderColor = '';
            }
        });

        updatePreview();
    }

    function setFormat(format) {
        currentFormat = format;
        const btnHtml = document.getElementById('btnFormatHtml');
        const btnText = document.getElementById('btnFormatText');

        if (format === 'html') {
            btnHtml.style.background = 'var(--brand-purple)';
            btnHtml.style.color = '#ffffff';
            btnText.style.background = 'transparent';
            btnText.style.color = 'var(--text-secondary)';
        } else {
            btnText.style.background = 'var(--brand-purple)';
            btnText.style.color = '#ffffff';
            btnHtml.style.background = 'transparent';
            btnHtml.style.color = 'var(--text-secondary)';
        }

        updatePreview();
    }

    function setViewport(width) {
        currentViewport = width;
        const btnDesk = document.getElementById('btnViewportDesktop');
        const btnMob = document.getElementById('btnViewportMobile');
        const btnFull = document.getElementById('btnViewportFull');

        [btnDesk, btnMob, btnFull].forEach(b => {
            b.style.background = 'transparent';
            b.style.color = 'var(--text-secondary)';
        });

        if (width === '600px') {
            btnDesk.style.background = 'var(--brand-purple)';
            btnDesk.style.color = '#ffffff';
        } else if (width === '380px') {
            btnMob.style.background = 'var(--brand-purple)';
            btnMob.style.color = '#ffffff';
        } else {
            btnFull.style.background = 'var(--brand-purple)';
            btnFull.style.color = '#ffffff';
        }

        const frameWrapper = document.getElementById('frameWrapper');
        frameWrapper.style.width = width;
    }

    function reloadEmailFrame() {
        const frame = document.getElementById('emailPreviewFrame');
        if (frame && currentFormat === 'html') {
            frame.src = `/emails/render/${currentTemplate}?format=html&t=${Date.now()}`;
        } else {
            updatePreview();
        }
    }

    function copyPlaintext(btn) {
        const content = document.getElementById('textPreviewContent').innerText;
        navigator.clipboard.writeText(content).then(() => {
            const orig = btn.innerText;
            btn.innerText = 'Copied!';
            btn.style.color = 'var(--brand-teal)';
            setTimeout(() => {
                btn.innerText = orig;
                btn.style.color = '';
            }, 1800);
        });
    }

    // Auto-adjust iframe height on load
    document.getElementById('emailPreviewFrame').addEventListener('load', function() {
        try {
            const doc = this.contentWindow.document;
            if (doc && doc.body) {
                const h = Math.max(doc.body.scrollHeight, 460);
                this.style.height = `${h + 20}px`;
            }
        } catch (e) {
            // cross-origin safeguard if applicable
        }
    });

    // Initialize active tab styling
    document.addEventListener('DOMContentLoaded', () => {
        const activeTab = document.querySelector('.email-tab.active');
        if (activeTab) {
            activeTab.style.background = 'rgba(168, 2, 245, 0.15)';
            activeTab.style.color = 'var(--param-name-color)';
            activeTab.style.borderColor = 'var(--brand-purple)';
        }
    });
</script>
@endsection
