services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comme_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=comme_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=aryarega2811
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - postgres
      - mailpit
    networks:
      - comme_network

  postgres:
    image: postgres:16-alpine
    container_name: comme_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: comme_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aryarega2811
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - comme_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: comme_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - comme_network

volumes:
  pgdata:
    driver: local

networks:
  comme_network:
    driver: bridge
